server:
  port: ${port:9091}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud
    username: root
    password: root
  application:
    name: User-Service

mybatis:
  type-aliases-package: cn.far.pojo
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
#    fetch-registry: false
#    register-with-eureka: false

  instance:
    ip-address: 127.0.0.1   # ip地址
    prefer-ip-address: true    # 更倾向于使用 ip，而不是主机名
    lease-renewal-interval-in-seconds: 5  # 服务续约时间，默认30s
    lease-expiration-duration-in-seconds: 5   # 服务失效时间，默认90s


